import type { Vehicle } from "@voltlist/shared";

const baseAdas = {
  systemName: "Highway Driving Assist",
  adaptiveCruiseControl: "Standard",
  laneKeepAssist: "Standard",
  laneCentering: "Standard",
  handsFreeHighway: "NotAvailable",
  automaticEmergencyBraking: "Standard",
  blindSpotMonitoring: "Standard",
  selfParking: "Optional",
  autonomyLevel: "SAE L2",
} satisfies Vehicle["adas"];

/** A representative BEV. */
export const bevFixture: Vehicle = {
  id: "test-ioniq-5-2026",
  make: "Hyundai",
  model: "Ioniq 5",
  year: 2026,
  trimsSummary: "SE, SEL, Limited",
  bodyStyle: "Crossover",
  powertrainType: "BEV",
  segment: "Compact SUV",
  electricRangeMi: 303,
  totalRangeMi: 303,
  mpge: 114,
  mpgCombined: null,
  efficiencyMiPerKwh: 3.3,
  batteryKwhUsable: 84,
  batteryKwhTotal: 87,
  fuelTankGal: null,
  dcFastMaxKw: 257,
  dcFast10to80Min: 20,
  acOnboardKw: 11,
  chargePort: "NACS",
  drivetrain: "AWD",
  motorLayout: "Dual motor",
  horsepower: 320,
  torqueLbFt: 446,
  zeroToSixtySec: 4.5,
  topSpeedMph: 115,
  towingCapacityLb: 2300,
  adas: baseAdas,
  lengthIn: 182.5,
  widthIn: 74.4,
  heightIn: 63.2,
  wheelbaseIn: 118.1,
  groundClearanceIn: 6.1,
  cargoCuFt: 27.2,
  frunkCuFt: 0.85,
  seatingCapacity: 5,
  curbWeightLb: 4662,
  msrpBaseUsd: 46550,
  msrpTopUsd: 58100,
  federalTaxCreditEligible: true,
  federalTaxCreditNote: "Assembled in USA",
  warrantyBasic: "5 yr / 60,000 mi",
  warrantyPowertrain: "10 yr / 100,000 mi",
  warrantyBattery: "10 yr / 100,000 mi",
  buildAndPriceUrl: "https://www.hyundaiusa.com/us/en/vehicles/ioniq-5",
  manufacturerUrl: "https://www.hyundaiusa.com",
  sources: [{ url: "https://www.fueleconomy.gov", asOf: "2026-01-15" }],
  dataAsOf: "2026-01-15",
  trims: [],
};

/** A representative PHEV. */
export const phevFixture: Vehicle = {
  id: "test-rav4-prime-2026",
  make: "Toyota",
  model: "RAV4 Prime",
  year: 2026,
  trimsSummary: "SE, XSE",
  bodyStyle: "SUV",
  powertrainType: "PHEV",
  segment: "Compact SUV",
  electricRangeMi: 42,
  totalRangeMi: 600,
  mpge: 94,
  mpgCombined: 38,
  efficiencyMiPerKwh: null,
  batteryKwhUsable: 18.1,
  batteryKwhTotal: 18.1,
  fuelTankGal: 14.5,
  dcFastMaxKw: null,
  dcFast10to80Min: null,
  acOnboardKw: 6.6,
  chargePort: "J1772",
  drivetrain: "AWD",
  motorLayout: "Dual motor + engine",
  horsepower: 302,
  torqueLbFt: 199,
  zeroToSixtySec: 5.7,
  topSpeedMph: 112,
  towingCapacityLb: 2500,
  adas: baseAdas,
  lengthIn: 180.9,
  widthIn: 73,
  heightIn: 67,
  wheelbaseIn: 105.9,
  groundClearanceIn: 8.1,
  cargoCuFt: 33.5,
  frunkCuFt: null,
  seatingCapacity: 5,
  curbWeightLb: 4300,
  msrpBaseUsd: 44265,
  msrpTopUsd: 47825,
  federalTaxCreditEligible: false,
  federalTaxCreditNote: null,
  warrantyBasic: "3 yr / 36,000 mi",
  warrantyPowertrain: "5 yr / 60,000 mi",
  warrantyBattery: "10 yr / 150,000 mi",
  buildAndPriceUrl: "https://www.toyota.com/rav4prime",
  manufacturerUrl: "https://www.toyota.com",
  sources: [{ url: "https://www.fueleconomy.gov", asOf: "2026-01-10" }],
  dataAsOf: "2026-01-10",
  trims: [],
};

/** A representative HEV. */
export const hevFixture: Vehicle = {
  id: "test-camry-hybrid-2026",
  make: "Toyota",
  model: "Camry Hybrid",
  year: 2026,
  trimsSummary: "LE, SE, XLE, XSE",
  bodyStyle: "Sedan",
  powertrainType: "HEV",
  segment: "Midsize Sedan",
  electricRangeMi: null,
  totalRangeMi: 663,
  mpge: null,
  mpgCombined: 51,
  efficiencyMiPerKwh: null,
  batteryKwhUsable: null,
  batteryKwhTotal: 1.6,
  fuelTankGal: 13,
  dcFastMaxKw: null,
  dcFast10to80Min: null,
  acOnboardKw: null,
  chargePort: null,
  drivetrain: "FWD",
  motorLayout: "Hybrid transaxle",
  horsepower: 225,
  torqueLbFt: 163,
  zeroToSixtySec: 7.2,
  topSpeedMph: 121,
  towingCapacityLb: null,
  adas: baseAdas,
  lengthIn: 193.5,
  widthIn: 72.2,
  heightIn: 56.9,
  wheelbaseIn: 111.2,
  groundClearanceIn: 5.7,
  cargoCuFt: 15.1,
  frunkCuFt: null,
  seatingCapacity: 5,
  curbWeightLb: 3560,
  msrpBaseUsd: 29200,
  msrpTopUsd: 34900,
  federalTaxCreditEligible: false,
  federalTaxCreditNote: null,
  warrantyBasic: "3 yr / 36,000 mi",
  warrantyPowertrain: "5 yr / 60,000 mi",
  warrantyBattery: "10 yr / 150,000 mi",
  buildAndPriceUrl: "https://www.toyota.com/camry",
  manufacturerUrl: "https://www.toyota.com",
  sources: [{ url: "https://www.fueleconomy.gov", asOf: "2026-01-08" }],
  dataAsOf: "2026-01-08",
  trims: [],
};

export const carFixtures: Vehicle[] = [bevFixture, phevFixture, hevFixture];
